-- Tighten Data API grants for Dompet Santri tables.
-- RLS remains the primary row filter; these grants remove broad direct mutation
-- capability from browser/mobile clients.

revoke all on table
  public.dompet_santri,
  public.crypto_keystores,
  public.wallet_devices,
  public.wallet_payment_intents,
  public.wallet_authorization_sessions,
  public.transaksi_dompet,
  public.wallet_nonces,
  public.wallet_nonce_uses,
  public.wallet_card_qr_versions,
  public.wallet_key_rotation_logs,
  public.wallet_audit_logs,
  public.wallet_merchants,
  public.wallet_merchant_outlets,
  public.wallet_merchant_users,
  public.wallet_card_tokens,
  public.wallet_system_controls,
  public.wallet_reconciliation_runs,
  public.wallet_risk_events,
  public.kantin_devices,
  public.wallet_disputes,
  public.wallet_ledger_integrity_runs,
  public.wallet_pin_attempts,
  public.wallet_weekly_digest_runs,
  public.wallet_security_audit_runs
from anon;

revoke all on table
  public.dompet_santri,
  public.crypto_keystores,
  public.wallet_devices,
  public.wallet_payment_intents,
  public.wallet_authorization_sessions,
  public.transaksi_dompet,
  public.wallet_nonces,
  public.wallet_nonce_uses,
  public.wallet_card_qr_versions,
  public.wallet_key_rotation_logs,
  public.wallet_audit_logs,
  public.wallet_merchants,
  public.wallet_merchant_outlets,
  public.wallet_merchant_users,
  public.wallet_card_tokens,
  public.wallet_system_controls,
  public.wallet_reconciliation_runs,
  public.wallet_risk_events,
  public.kantin_devices,
  public.wallet_disputes,
  public.wallet_ledger_integrity_runs,
  public.wallet_pin_attempts,
  public.wallet_weekly_digest_runs,
  public.wallet_security_audit_runs
from authenticated;

grant select on table
  public.dompet_santri,
  public.crypto_keystores,
  public.wallet_devices,
  public.wallet_payment_intents,
  public.wallet_authorization_sessions,
  public.transaksi_dompet,
  public.wallet_nonces,
  public.wallet_nonce_uses,
  public.wallet_card_qr_versions,
  public.wallet_key_rotation_logs,
  public.wallet_audit_logs,
  public.wallet_merchants,
  public.wallet_merchant_outlets,
  public.wallet_merchant_users,
  public.wallet_card_tokens,
  public.wallet_system_controls,
  public.wallet_reconciliation_runs,
  public.wallet_risk_events,
  public.kantin_devices,
  public.wallet_disputes,
  public.wallet_ledger_integrity_runs,
  public.wallet_pin_attempts,
  public.wallet_weekly_digest_runs,
  public.wallet_security_audit_runs
to authenticated;
